version: "2.24"

networks:
    laravel:
        name: ${COMPOSE_PROJECT_NAME}-laravel
        driver: bridge

services:

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        image: nginx:${NGINX_VERSION}-alpine
        ports:
            - ${FORWARD_NGINX_PORT:-80}:80
        depends_on:
            - php
            - mysql
            - redis
        volumes:
            - ${PATH_SRC}:/var/www/html
            - ${PATH_SERVICES}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            context: .
            dockerfile: ${PATH_SERVICES}/php/dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
                - UID=${UID:-1000}
                - USER_NAME=${USER_NAME:-laravel}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - LARAVEL_VERSION=${LARAVEL_VERSION}
        volumes:
            - ${PATH_SRC}:/var/www/html
        ports:
            - ${FORWARD_PHP_PORT:-9000}:9000
        networks:
            - laravel

    mysql:
        image: mariadb:${MARIA_DB_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        restart: unless-stopped
        tty: true
        ports:
            - ${FORWARD_MYSQL_PORT:-3306}:3306
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laraveldb}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
            TZ: "America/Argentina/Buenos_Aires"
        volumes:
            - ${PATH_DATA_MYSQL}:/var/lib/mysql
        networks:
            - laravel

    composer:
        image: composer:${COMPOSER_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-composer
        working_dir: /var/www/html
        volumes:
            - ${PATH_SRC}:/var/www/html
        entrypoint: [ 'composer' ]
        networks:
            - laravel

    artisan:
        container_name: ${COMPOSE_PROJECT_NAME}-artisan
        build:
            context: .
            dockerfile: ${PATH_SERVICES}/php/dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
                - UID=${UID:-1000}
                - USER_NAME=${USER_NAME:-laravel}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - LARAVEL_VERSION=${LARAVEL_VERSION}
        entrypoint: ['php', '/var/www/html/artisan']
        volumes:
            - ${PATH_SRC}:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    npm:
        image: node:${NODE_VERSION}-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-npm
        volumes:
            - ${PATH_SRC}:/var/www/html
        ports:
            - ${FORWARD_NPM_PORT_1:-3000}:3000
            - ${FORWARD_NPM_PORT_2:-5173}:5173
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    redis:
        image: redis:${REDIS_VERSION}-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: unless-stopped
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        networks:
            - laravel
