ARG COMPOSER_VERSION=$COMPOSER_VERSION
ARG PHP_VERSION=$PHP_VERSION
ARG NODE_VERSION=$NODE_VERSION

# Multi stage de Composer
FROM composer:${COMPOSER_VERSION} AS composer

# Multi stage de NodeJS
FROM node:${NODE_VERSION}-alpine AS node

FROM php:${PHP_VERSION}-fpm-alpine

ARG UID=$UID
ARG USER_NAME=$USER_NAME

RUN adduser -G root --system -D -s /bin/sh -u ${UID} ${USER_NAME}

# Crear directorio para la aplicación
RUN mkdir -p /var/www/html

WORKDIR /var/www/html

# Instalar librerias necesarias
RUN apk add --no-cache --virtual .build-deps \
    $PHPIZE_DEPS \
    oniguruma-dev \
    postgresql-dev \
    sqlite-dev \
    libxml2-dev \
    gmp-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    libzip-dev \
    freetype-dev \
    curl

# Instalar extensiones de PHP necesarias
RUN docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl soap xml mysqli gd

RUN apk add --no-cache \
    libpng-dev \
    openldap-dev \
    icu-dev \
    libwebp-dev \
    libzip \
    libwebp-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp

# Instalación de Composer
# ARG COMPOSER_VERSION=$COMPOSER_VERSION

# Descarga el instalador de Composer
# RUN curl -sS https://getcomposer.org/installer -o composer-setup.php

# Verifica el instalador de Composer
# RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Instalador de Composer válido'; } else { echo 'Instalador de Composer corrupto'; unlink('composer-setup.php'); exit(1); }"

# Ejecuta el instalador de Composer
# RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION}

# Elimina el instalador de Composer
# RUN rm composer-setup.php
# Fin instalación de Composer

# Copia el ejecutable de Composer desde la etapa de construcción
COPY --from=composer /usr/bin/composer /usr/bin/composer

# # Copia el ejecutable de NodeJs desde la etapa de construcción
# COPY --from=node /usr/local/bin/node /usr/local/bin/node
# # Copia los archivos necesarios de npm
# RUN curl -L https://npmjs.org/install.sh | sh
# COPY --from=node /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
# COPY --from=node /usr/local/lib/node_modules/npm/lib /usr/local/lib/node_modules/npm/lib

# Limpia dependencias
RUN apk del .build-deps \
    && rm -rf /tmp/*

USER ${USER_NAME}
